### PR TITLE
Develop into Master for CI

### PR DESCRIPTION
**Pull request by jee7s**

### CODE REVIEW

**Review by dawilson9 — DISMISSED** [review]
This merge is pulling in a bunch of inactive code that should probably be deleted or moved somewhere out of the way. Given that we're not really using the master branch properly (yet), though, I'm going to press "Approve" to see what happens :-)

**Review by dpeeps — COMMENTED** [review]
With the merge errors fixed, the code still needs to be validated as at least working in a basic sense, then fixing the errors with PID and others.

**Comment by dawilson9** [comment]
I'm not 100% sure that I understand what's going on here since I see a merge from master into develop here. In normal operation, we merge from develop into master whenever develop contains a good, working, tested build. We shouldn't be merging back up to develop at any point. Looking at the deltas, though, they seem benign (mostly whitespace changes) so maybe this was just a cleanup thing to ensure common files remain common?

**Comment by jee7s** [comment]
@dpeeps I think we want to back out that last commit. We need to resolve a bunch of diffs from develop to master, but simply merging master to develop is not the right approach. In this case, it probably works, but it's not a habit we want to get into.

**Comment by dpeeps** [comment]
I can agree with that, the main things that were changed we're redundant things that we learned to fix throughout the season, updates, or different line numbers. In general the way the change path looked was that there were about 20 legitimate changes, that looking through, the develop branch had a majority of the path that we were trying to take at the end of the season. A lot of the changes in general will have to be looked at when there can be some more hands on time, to troubleshoot and test the path that we want to follow.

**Comment by dawilson9** [comment]
Note to self: Write up some documentation on our branching and tagging strategy if it's out of date and, more importantly, enforce it this season!!!!

**Review by dpeeps — APPROVED** [review]
The software has been tested on the robot, and has been tested. The arm is working, and has been fully fixed from the stupid errors. At this point it is better to merge onto master, and continue other work, but have a show ready system that can be quickly pulled off of master.

**Pull request merged**
